### ISSUE TITLE
Problems trying to install in 3.16 on windows 10

### ISSUE THREAD

**Issue by madepablohdez** [sbraden/circle-craters#24]
I am trying to install circle-craters component in QGIS 3.16 on windows 10.
There are not instructions in the github page of this component, so i downloaded a copy on zipfile.

i tried 2 different things:

1.  In QGIS, i went to Pluggings>Manage pluggins and then Install from zip. I located the file and tried the installation. An error was reported:
2. 

> It was not possible to load the pluggin 'circle-craters-master' due to an ellor colling the method classFactory() 

ModuleNotFoundError: No module named 'CircleCraters' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/miguelangel.depablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\circle-craters-master\__init__.py", line 34, in classFactory
    from .circle_craters import CircleCraters
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/miguelangel.depablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\circle-craters-master\circle_craters.py", line 66, in 
    import CircleCraters.resources_rc
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'CircleCraters'

Versión de Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versión de QGIS: 3.16.11-Hannover Hannover, 26cc1c762f 

Path to Python:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/miguelangel.depablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/miguelangel.depablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/miguelangel.depablo/AppData/Roaming/QGIS/QGIS3\profiles\default/python'

2. I unzipped the file in ...Users\.qgis2\python folder. Then, in QGIS, pluggins> Pluggins manager, i saw circle-craters in the list of installed pluggings. However, by clicking on the box at the left to activate it, the same error is returned.

What am i doing wrong?

thanks so much!

**Comment by BerginJay** [comment]
Sadly, I don't think that this plugin is tested on Windows. You can try to install it by customizing the Makefile. 
Alternatively, the Makefile is just help you to copy plugin files into your QGIS directory, so I think maybe you can directly copy files into your QGIS directory by mimicking following commands in Makefile:
```
deploy: compile doc transcompile
	@echo
	@echo "------------------------------------------"
	@echo "Deploying plugin to your .qgis2/ .qgis3 directory."
	@echo "------------------------------------------"
	# The deploy  target only works on unix like operating system where
	# the Python plugin directory is located at:
	# ${HOME}/$(QGISDIR)/python/plugins
	mkdir -p $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)
	cp -vf $(PY_FILES) $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)
	cp -vf $(UI_FILES) $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)
	cp -vf $(COMPILED_RESOURCE_FILES) $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)
	cp -vf $(EXTRAS) $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)
	cp -vfr i18n $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)
	cp -vfr $(HELP) $(HOME)/$(QGISDIR)/python/plugins/$(PLUGINNAME)/help
```
What you need to do is just replace the path variables with your installation, and use the `copy` command with proper options in cmd/PowerShell instead of `cp` (Perhaps makefile would work well in WSL).
